# Generated by Django 3.1.14 on 2022-03-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryton_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='session_type',
            field=models.CharField(choices=[('MSF_SHELL', 'Metasploit console shell session'), ('MSF_METERPRETER', 'Metasploit meterpreter session')], default='MSF_METERPRETER', max_length=50),
            preserve_default=False,
        ),
    ]
