# Generated by Django 3.1.14 on 2022-04-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryton_rest_api', '0002_sessionmodel_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmodel',
            name='info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
