# Generated by Django 3.1.14 on 2022-05-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryton_rest_api', '0003_stepmodel_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='plan_info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
